### ISSUE TITLE
tab spacing is a little off

### ISSUE THREAD

**Issue by ceckenrode** [njwest/week-4-game#1]
It's a little too deep.

https://css-tricks.com/changing-spaces-tabs-sublime-text/

^ you only need to follow the first part of this. get your tab spacing to 2 spaces to prevent this issue. sublimes default is 4. everyone in the world uses 2

**Comment by njwest** [comment]
Thanks! I had tab_size: 3 before but did not have translate_tabs_to_spaces. Am now using tab_size: 2
